//! Page registry: every gallery page as a [`PageKind`], its Turkish title,
//! icon, and description, plus the mapping used by the search palette.

pub mod common;
pub mod components;
pub mod general;

use gpui_kit::assets::IconName;
use gpui_kit::component::IndexPath;
use gpui_kit::AnyView;

/// A gallery page. Pages are lazily created as views and cached for the
/// session, so demo state survives navigation.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]
pub enum PageKind {
    // Genel
    Overview,
    Colors,
    Typography,
    Theme,
    // Components
    Button,
    Checkbox,
    Switch,
    Radio,
    Input,
    Textarea,
    NumberInput,
    OtpInput,
    SearchInput,
    InputGroup,
    Select,
    ComboBox,
    Slider,
    Progress,
    Spinner,
    Tooltip,
    Popover,
    Badge,
    Tag,
    Separator,
    Kbd,
    Label,
    Link,
    List,
    Table,
    Tab,
    Accordion,
    Collapsible,
    Breadcrumb,
    Pagination,
    Avatar,
    Alert,
    Notification,
    Dialog,
    Sheet,
    ColorPicker,
    Calendar,
    Rating,
    Stepper,
    Tree,
    Chart,
}

pub const GENERAL: &[PageKind] = &[
    PageKind::Overview,
    PageKind::Colors,
    PageKind::Typography,
    PageKind::Theme,
];

pub const COMPONENTS: &[PageKind] = &[
    PageKind::Button,
    PageKind::Checkbox,
    PageKind::Switch,
    PageKind::Radio,
    PageKind::Input,
    PageKind::Textarea,
    PageKind::NumberInput,
    PageKind::OtpInput,
    PageKind::SearchInput,
    PageKind::InputGroup,
    PageKind::Select,
    PageKind::ComboBox,
    PageKind::Slider,
    PageKind::Progress,
    PageKind::Spinner,
    PageKind::Tooltip,
    PageKind::Popover,
    PageKind::Badge,
    PageKind::Tag,
    PageKind::Separator,
    PageKind::Kbd,
    PageKind::Label,
    PageKind::Link,
    PageKind::List,
    PageKind::Table,
    PageKind::Tab,
    PageKind::Accordion,
    PageKind::Collapsible,
    PageKind::Breadcrumb,
    PageKind::Pagination,
    PageKind::Avatar,
    PageKind::Alert,
    PageKind::Notification,
    PageKind::Dialog,
    PageKind::Sheet,
    PageKind::ColorPicker,
    PageKind::Calendar,
    PageKind::Rating,
    PageKind::Stepper,
    PageKind::Tree,
    PageKind::Chart,
];

impl PageKind {
    pub fn title(self) -> &'static str {
        match self {
            Self::Overview => "Overview",
            Self::Colors => "Colors",
            Self::Typography => "Typography",
            Self::Theme => "Theme",
            Self::Button => "Button",
            Self::Checkbox => "Checkbox",
            Self::Switch => "Switch",
            Self::Radio => "Radio",
            Self::Input => "Input",
            Self::Textarea => "Textarea",
            Self::NumberInput => "Number Input",
            Self::OtpInput => "OTP Input",
            Self::SearchInput => "Search",
            Self::InputGroup => "Input Group",
            Self::Select => "Select",
            Self::ComboBox => "ComboBox",
            Self::Slider => "Slider",
            Self::Progress => "Progress",
            Self::Spinner => "Spinner",
            Self::Tooltip => "Tooltip",
            Self::Popover => "Popover",
            Self::Badge => "Badge",
            Self::Tag => "Tag",
            Self::Separator => "Separator",
            Self::Kbd => "Kbd",
            Self::Label => "Label",
            Self::Link => "Link",
            Self::List => "List",
            Self::Table => "Table",
            Self::Tab => "Tab",
            Self::Accordion => "Accordion",
            Self::Collapsible => "Collapsible",
            Self::Breadcrumb => "Breadcrumb",
            Self::Pagination => "Pagination",
            Self::Avatar => "Avatar",
            Self::Alert => "Alert",
            Self::Notification => "Notification",
            Self::Dialog => "Dialog",
            Self::Sheet => "Sheet",
            Self::ColorPicker => "Color Picker",
            Self::Calendar => "Calendar",
            Self::Rating => "Rating",
            Self::Stepper => "Stepper",
            Self::Tree => "Tree",
            Self::Chart => "Chart",
        }
    }

    pub fn description(self) -> &'static str {
        match self {
            Self::Overview => "OzdemirGPUIThemePack: a Fluent 2 theme pack for gpui-kit with a live-preview gallery.",
            Self::Colors => "Fluent 2 accent ramps, grey shades, and semantic colors — straight from the Rust token source.",
            Self::Typography => "The Segoe UI Variable type ramp: size, line height, and weight.",
            Self::Theme => "16 theme variants (8 accents × light/dark) — click a card to apply it live.",
            Self::Button => "Every button variant, size, loading state, and grouping behavior.",
            Self::Checkbox => "Checkboxes: labeled, disabled, and controlled usage.",
            Self::Switch => "Toggles: labeled, disabled, and controlled usage.",
            Self::Radio => "Radio groups: single choice and dynamic options.",
            Self::Input => "Text input: placeholder, prefix/suffix, and validation contexts.",
            Self::Textarea => "Multiline text input.",
            Self::NumberInput => "Numeric input with step buttons.",
            Self::OtpInput => "One-time code (OTP) input.",
            Self::SearchInput => "Search-style inputs.",
            Self::InputGroup => "Composed input groups: buttons and inputs in one frame.",
            Self::Select => "Dropdown list selection.",
            Self::ComboBox => "Filterable combo box.",
            Self::Slider => "Single-value slider with live value tracking.",
            Self::Progress => "Progress bars and circular indicators.",
            Self::Spinner => "Loading spinners.",
            Self::Tooltip => "Tooltips and their placements.",
            Self::Popover => "Popovers anchored to a trigger.",
            Self::Badge => "Small status badges.",
            Self::Tag => "Tags and chips.",
            Self::Separator => "Horizontal and vertical separators.",
            Self::Kbd => "Keyboard key indicators.",
            Self::Label => "Labels and text styles.",
            Self::Link => "Links.",
            Self::List => "Lists and list items.",
            Self::Table => "Data tables.",
            Self::Tab => "Tab bars and tabs.",
            Self::Accordion => "Accordion panels.",
            Self::Collapsible => "Expandable/collapsible regions.",
            Self::Breadcrumb => "Page path breadcrumbs.",
            Self::Pagination => "Pagination controls.",
            Self::Avatar => "User avatars and groups.",
            Self::Alert => "Alert boxes: info, success, warning, error.",
            Self::Notification => "Notifications.",
            Self::Dialog => "Dialogs and confirm boxes.",
            Self::Sheet => "Edge sheets.",
            Self::ColorPicker => "Color pickers.",
            Self::Calendar => "Calendar and date picker.",
            Self::Rating => "Star ratings.",
            Self::Stepper => "Stepper flows.",
            Self::Tree => "Tree views.",
            Self::Chart => "Charts: bar, line, and pie.",
        }
    }

    pub fn icon(self) -> IconName {
        use IconName as I;
        match self {
            Self::Overview => I::LayoutDashboard,
            Self::Colors => I::Palette,
            Self::Typography => I::Type,
            Self::Theme => I::GalleryVerticalEnd,
            Self::Button => I::MousePointerClick,
            Self::Checkbox => I::SquareCheckBig,
            Self::Switch => I::ToggleLeft,
            Self::Radio => I::CircleDot,
            Self::Input => I::TextCursorInput,
            Self::Textarea => I::SquareMenu,
            Self::NumberInput => I::Hash,
            Self::OtpInput => I::KeyRound,
            Self::SearchInput => I::Search,
            Self::InputGroup => I::Group,
            Self::Select => I::ChevronsUpDown,
            Self::ComboBox => I::Box,
            Self::Slider => I::SlidersHorizontal,
            Self::Progress => I::Gauge,
            Self::Spinner => I::LoaderCircle,
            Self::Tooltip => I::Info,
            Self::Popover => I::SquareDashed,
            Self::Badge => I::Badge,
            Self::Tag => I::Tag,
            Self::Separator => I::SeparatorHorizontal,
            Self::Kbd => I::Command,
            Self::Label => I::ALargeSmall,
            Self::Link => I::Link,
            Self::List => I::List,
            Self::Table => I::Table,
            Self::Tab => I::SquareStack,
            Self::Accordion => I::ChevronsDownUp,
            Self::Collapsible => I::ChevronDown,
            Self::Breadcrumb => I::CornerDownRight,
            Self::Pagination => I::ArrowLeftRight,
            Self::Avatar => I::CircleUser,
            Self::Alert => I::TriangleAlert,
            Self::Notification => I::Bell,
            Self::Dialog => I::MessageSquare,
            Self::Sheet => I::PanelBottom,
            Self::ColorPicker => I::Pipette,
            Self::Calendar => I::Calendar,
            Self::Rating => I::Star,
            Self::Stepper => I::Plus,
            Self::Tree => I::ListTree,
            Self::Chart => I::ChartColumn,
        }
    }
}

/// Resolve a search-palette [`IndexPath`] back to its page. The palette is
/// built from [`GENERAL`] followed by [`COMPONENTS`], each as one group.
pub fn page_at(index: &IndexPath) -> Option<PageKind> {
    match index.section {
        0 => GENERAL.get(index.row).copied(),
        1 => COMPONENTS.get(index.row).copied(),
        _ => None,
    }
}

/// Create the lazily initialized view for a page.
pub fn make(kind: PageKind, window: &mut gpui_kit::Window, cx: &mut gpui_kit::App) -> AnyView {
    use components as c;
    use general as g;

    match kind {
        PageKind::Overview => g::OverviewPage::view(window, cx),
        PageKind::Colors => g::ColorsPage::view(window, cx),
        PageKind::Typography => g::TypographyPage::view(window, cx),
        PageKind::Theme => g::ThemePage::view(window, cx),
        PageKind::Button => c::ButtonPage::view(window, cx),
        PageKind::Checkbox => c::CheckboxPage::view(window, cx),
        PageKind::Switch => c::SwitchPage::view(window, cx),
        PageKind::Radio => c::RadioPage::view(window, cx),
        PageKind::Input => c::InputPage::view(window, cx),
        PageKind::Textarea => c::TextareaPage::view(window, cx),
        PageKind::NumberInput => c::NumberInputPage::view(window, cx),
        PageKind::OtpInput => c::OtpInputPage::view(window, cx),
        PageKind::SearchInput => c::SearchInputPage::view(window, cx),
        PageKind::InputGroup => c::InputGroupPage::view(window, cx),
        PageKind::Select => c::SelectPage::view(window, cx),
        PageKind::ComboBox => c::ComboBoxPage::view(window, cx),
        PageKind::Slider => c::SliderPage::view(window, cx),
        PageKind::Progress => c::ProgressPage::view(window, cx),
        PageKind::Spinner => c::SpinnerPage::view(window, cx),
        PageKind::Tooltip => c::TooltipPage::view(window, cx),
        PageKind::Popover => c::PopoverPage::view(window, cx),
        PageKind::Badge => c::BadgePage::view(window, cx),
        PageKind::Tag => c::TagPage::view(window, cx),
        PageKind::Separator => c::SeparatorPage::view(window, cx),
        PageKind::Kbd => c::KbdPage::view(window, cx),
        PageKind::Label => c::LabelPage::view(window, cx),
        PageKind::Link => c::LinkPage::view(window, cx),
        PageKind::List => c::ListPage::view(window, cx),
        PageKind::Table => c::TablePage::view(window, cx),
        PageKind::Tab => c::TabPage::view(window, cx),
        PageKind::Accordion => c::AccordionPage::view(window, cx),
        PageKind::Collapsible => c::CollapsiblePage::view(window, cx),
        PageKind::Breadcrumb => c::BreadcrumbPage::view(window, cx),
        PageKind::Pagination => c::PaginationPage::view(window, cx),
        PageKind::Avatar => c::AvatarPage::view(window, cx),
        PageKind::Alert => c::AlertPage::view(window, cx),
        PageKind::Notification => c::NotificationPage::view(window, cx),
        PageKind::Dialog => c::DialogPage::view(window, cx),
        PageKind::Sheet => c::SheetPage::view(window, cx),
        PageKind::ColorPicker => c::ColorPickerPage::view(window, cx),
        PageKind::Calendar => c::CalendarPage::view(window, cx),
        PageKind::Rating => c::RatingPage::view(window, cx),
        PageKind::Stepper => c::StepperPage::view(window, cx),
        PageKind::Tree => c::TreePage::view(window, cx),
        PageKind::Chart => c::ChartPage::view(window, cx),
    }
}
